// Vue-projects/VueTodoApp2/src/components/Form.vue
<template>
  <form>
    <input type="text" placeholder="Enter a todo" v-model="name" />
    <button @click.prevent="addTodo">Add Todo</button>
  </form>
</template>

<script>
export default {
  data() {
    return {
      name: "",
    };
  },
  methods: {
    addTodo(e) {
      this.$emit("addNewTodo", {
        id: self.crypto.randomUUID(),
        name: this.name,
        isComplete: false,
      });
      this.name = "";
    },
  },
};
</script>

<style></style>

// React projects/Todo App/src/components/Form.jsx
import { useRef } from "react"
import PropTypes from 'prop-types'

const Form = ({ allTodos, setAllTodos }) => {
    const inputRef = useRef()

    const addItem = (e) => {
        e.preventDefault();
        inputRef.current.value == "" ? alert("lütfen bir todo gir") :
            setAllTodos([{
                id: self.crypto.randomUUID(),
                name: inputRef.current.value,
                isComplete: false,
                isEdit: false
            }, ...allTodos]);
        inputRef.current.value = "";
    }
    return (
        <form onSubmit={(e) => addItem(e)}>
            <input type="text" placeholder="Please enter a content!" ref={inputRef} />
            <button type="submit">Add</button>
        </form>
    )
}

Form.propTypes = {
    allTodos: PropTypes.array,
    setAllTodos: PropTypes.func
}
export default Form
