// Preact-projects/PreactTodoApp/src/components/Form.jsx
import { useState, useRef } from 'preact/hooks'
// import PropTypes from 'prop-types'
import Modal from "./Modal";

const Form = ({ allTodos, setAllTodos }) => {
    const inputRef = useRef()
    const [isModalOpen, setIsModalOpen] = useState(false);

    const closeAfterDelay = () => {
        setTimeout(() => {
            setIsModalOpen(false);
        }, 1500);
    };

    const addItem = (e) => {
        e.preventDefault();
        inputRef.current.value == "" ?
            (
                setIsModalOpen(true),
                closeAfterDelay()
            ) :
            setAllTodos([
                {
                    id: self.crypto.randomUUID(),
                    name: inputRef.current.value,
                    isComplete: false,
                    isEdit: false
                },
                ...allTodos
            ]);
        inputRef.current.value = "";
    }

    return (
        <div>
            <form onSubmit={(e) => addItem(e)}>
                <input type="text" placeholder="Please enter a content!" ref={inputRef} />
                <button type="submit">Add</button>
            </form>
            {isModalOpen && (
                <Modal message="Please enter a content !!!" />
            )}
        </div>
    )
}

// Form.propTypes = {
//     allTodos: PropTypes.array,
//     setAllTodos: PropTypes.func
// }
export default Form

// Vue-projects/VueTodoApp2/src/components/Form.vue
<template>
  <form>
    <input type="text" placeholder="Enter a todo" v-model="name" />
    <button @click.prevent="addTodo">Add Todo</button>
  </form>
</template>

<script>
export default {
  data() {
    return {
      name: "",
    };
  },
  methods: {
    addTodo(e) {
      this.$emit("addNewTodo", {
        id: self.crypto.randomUUID(),
        name: this.name,
        isComplete: false,
      });
      this.name = "";
    },
  },
};
</script>

<style></style>
