// Preact-projects/PreactWeatherApp2/src/views/Homeview.jsx
import { useState } from "preact/hooks"
import EnterForm from "../components/EnterForm"
import Loading from "../components/Loading"
import DisplayLocationData from "../components/DisplayLocationData"

const Homeview = () => {
  const [locationData, setLocationData] = useState()
  const [cityName, setCityName] = useState("Kayseri")
  return (
    <>
      <h1 className="main-title">Weather App with Preact</h1>
      <EnterForm cityName={cityName} setCityName={setCityName} setLocationData={setLocationData} />
      {
        locationData == null ? <Loading /> : <DisplayLocationData locationData={locationData} />
      }
    </>
  )
}

export default Homeview

// Vue-projects/VueWeatherApp/src/views/HomeView.vue
<template>
  <main>
    <h1 className="main-title">Weather App with Vue</h1>
    <EnterForm :cityName="cityName" @searchCity="handleSearch" />
    <DisplayLocation
      v-if="cityDatas"
      :citySummaryData="cityDatas[0]"
      :cityDetailData="cityDatas[1]"
    />
    <Loading v-else />
  </main>
</template>

<script>
import EnterForm from "../components/EnterForm.vue";
import Loading from "../components/Loading.vue";
import DisplayLocation from "../components/DisplayLocation.vue";

import { getApiData } from "../request/request";

export default {
  components: { EnterForm, DisplayLocation, Loading },
  data() {
    return {
      cityName: "Kayseri",
      cityDatas: null,
    };
  },
  methods: {
    handleSearch(newCity) {
      this.cityName = newCity;
      getApiData(this.cityName).then((data) => {
        this.cityDatas = data;
      });
    },
  },
  mounted() {
    getApiData(this.cityName).then((data) => {
      this.cityDatas = data;
    });
  },
};
</script>
